export enum WORKFLOW_PROGRESS_STATUS_ENUM {
  PENDING = "Pending",
  APPROVED = "Approved",
  REJECTED = "Rejected",
  GL_CODE_ASSIGNED = "GL CODE ASSIGNED",
  JV_CREATED = "JV CREATED",
  JV_APPROVED = "JV APPROVED",
  PAYMENT_PROCESSED = "PAYMENT PROCESSED",
}

export const WORKFLOW_PROGRESS_LABEL: Record<
  WORKFLOW_PROGRESS_STATUS_ENUM,
  string
> = {
  [WORKFLOW_PROGRESS_STATUS_ENUM.PENDING]: "Submitted",
  [WORKFLOW_PROGRESS_STATUS_ENUM.APPROVED]: "Approved",
  [WORKFLOW_PROGRESS_STATUS_ENUM.REJECTED]: "Rejected",
  [WORKFLOW_PROGRESS_STATUS_ENUM.GL_CODE_ASSIGNED]: "GL Code Assigned",
  [WORKFLOW_PROGRESS_STATUS_ENUM.JV_CREATED]: "JV Created in SAP",
  [WORKFLOW_PROGRESS_STATUS_ENUM.JV_APPROVED]: "JV Approved",
  [WORKFLOW_PROGRESS_STATUS_ENUM.PAYMENT_PROCESSED]: "Payment Processed",
};
