export const ENDPOINTS = {
  EXPENSES: {
    UPLOAD: "v1/expenses",
    LIST: "v1/expenses",
    LINK: (expenseId: number) => `v1/expenses/${expenseId}/link`,
    DETAIL: (id: number) => `v1/expenses/${id}`,
    SUBMIT: (id: number) => `v1/expenses/${id}/submit`,
    DELETE: (id: number) => `v1/expenses/${id}`,
    TEAM: "v1/expenses/team",
    EXTRACT: (id: number) => `v1/expenses/${id}/extract`,
    DELETE_ALL: "v1/expenses/delete-all",
  },
  CONNECTION: {
    GET_ALL: "v1/connections",
    UPDATE: (id: number) => `v1/connections/${id}/configure`,
    DISCONNECT: (id: number) => `v1/connections/${id}/disconnect`,
    DELETE: (id: number) => `v1/connections/${id}`,
    TALLY: "v1/connections/tally",
    WHATSAPP: "v1/connections/whatsapp",
    GET: (id: number) => `v1/connections/${id}`,
    ACCESS_TOKEN: (id: number) => `v1/connections/${id}/token`,
    LABELS: (id: number) => `v1/connections/${id}/labels`,
    FOLDERS: (id: number) => `v1/connections/${id}/folders`,
    RECONNECT: (id: number) => `v1/connections/${id}/reconnect`,
  },
  DASHBOARD: {
    INFO: "v1/dashboard/",
    CATEGORY: "v1/dashboard/category",
    EMPLOYEE: "v1/dashboard/employee",
    TEAM_EXPENSE: "v1/dashboard/team-expenses",
    ADMIN: "v1/dashboard/admin",
    MANAGER: "v1/dashboard/manager",
  },
  AUTH: {
    LOGOUT: "v1/logout",
    ME: "v1/users/me",
  },
  GRADES: {
    ADD: "v1/grades/",
    LIST: "v1/grades/",
    UPDATE: (gradeId: number) => `v1/grades/${gradeId}`,
    UPLOAD_FILE: "v1/grades/upload",
    DELETE: (gradeId: number) => `v1/grades/${gradeId}`,
    TEMPLATE: "v1/grades/template",
  },
  EMPLOYEE: {
    ADD: "v1/users",
    LIST: "v1/users",
    UPDATE: (id: number) => `v1/users/${id}`,
    UPLOAD_FILE: "v1/users/upload",
    DELETE: (employeeId: number) => `v1/users/${employeeId}`,
    TEMPLATE: "v1/users/template",
    MANAGERS: "v1/users/managers",
    TEAM_MEMBERS: "v1/users/team-members",
    OPTIONS: "v1/users/options",
  },
  PROJECT: {
    LIST: "v1/projects",
    ADD: "v1/projects",
    GET: (id: number) => `v1/projects/${id}`,
    UPDATE: (id: number) => `v1/projects/${id}`,
    DELETE: (projectId: number) => `v1/projects/${projectId}`,
    MY: "v1/projects/my",
    UPLOAD: "v1/projects/upload",
    TEMPLATE: "v1/projects/template",
  },
  ROLES: {
    LIST: "v1/roles",
  },
  NOTIFICATIONS: {
    LIST: "v1/notifications/",
    STREAM: "v1/notifications/stream",
    READ_ALL: "v1/notifications/read-all",
    READ: (id: number) => `v1/notifications/${id}/read`,
  },
  ASSETS: {
    ADD: "v1/assets",
    LIST: "v1/assets",
    UPDATE: (assetId: number) => `v1/assets/${assetId}`,
    DELETE: (assetId: number) => `v1/assets/${assetId}`,
  },
  USER_EXPENSE: {
    STATUS: (userExpenseId: number) =>
      `v1/user-expenses/${userExpenseId}/status`,
  },
  REPORTS: {
    ME: "v1/reports/me",
    TEAM: "v1/reports/team",
  },
  TRAVEL_EXPENSE: {
    ADD: "v1/travel-expenses",
    TEAM: "v1/travel-expenses/team",
    NOTES: "v1/travel-expenses/notes",
    METRICS: "v1/travel-expenses/dashboard-metrics",
    TEAM_METRICS: "v1/travel-expenses/team/dashboard-metrics",
    MILEAGE_RATE: "v1/travel-expenses/mileage-rate",
    DETAIL: (id: number) => `v1/travel-expenses/${id}`,
    UPDATE: (id: number) => `v1/travel-expenses/${id}`,
    REJECT: (id: number) => `v1/travel-expenses/reject/${id}`,
    APPROVE: (id: number) => `v1/travel-expenses/approve/${id}`,
    GET_NOTES: (id: number) => `v1/travel-expenses/notes/${id}`,
  },
  DEPARTMENTS: {
    ADD: "v1/departments/",
    LIST: "v1/departments/",
    DELETE: (id: number) => `v1/departments/${id}`,
    UPDATE: (id: number) => `v1/departments/${id}`,
  },
  COST_CENTERS: {
    ADD: "v1/cost-centers/",
    LIST: "v1/cost-centers/",
    UPDATE: (id: number) => `v1/cost-centers/${id}`,
    DELETE: (id: number) => `v1/cost-centers/${id}`,
  },
  TRIPS: {
    LIST: "v1/trips/",
    OPTIONS: "v1/trips/options",
    TEAM: "v1/trips/team",
    ADD: "v1/trips/",
    UPDATE: (id: number) => `v1/trips/${id}`,
    DELETE: (id: number) => `v1/trips/${id}`,
    STATUS: (id: number) => `v1/trips/${id}/status`,
  },
};
