trigger:
  branches:
    include:
      - main

stages:
  - stage: Deploy
    displayName: Deploy to Staging VM
    jobs:
      - deployment: DeployExpenseWeb
        displayName: Deploying the Expense Web to Staging
        environment:
          name: Staging
          resourceName: z-transact-api-stg
          resourceType: virtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - script: |
                    rsync -av --delete ./ /home/ztransact/z-transact/Expense-Web --exclude='.env'
                  displayName: "Copying the files to destination"

                - script: |
                    echo "Building and starting containers..."
                    cd /home/ztransact/z-transact/Expense-Web
                    sudo docker compose up -d --build
                    echo "Containers started successfully"
                  displayName: "Build and Start Containers"
