"""add name column in organizations

Revision ID: 00e0188105f8
Revises: bd1f364f1a00
Create Date: 2026-01-14 17:50:26.053097

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "00e0188105f8"
down_revision: Union[str, Sequence[str], None] = "bd1f364f1a00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organizations", sa.Column("name", sa.String(), nullable=True))
    op.execute(
        """
        UPDATE organizations
        SET name = 'org_' || id::text
        WHERE name IS NULL
    """
    )
    op.alter_column("organizations", "name", nullable=False)
    op.create_unique_constraint("uq_organizations_name", "organizations", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_organizations_name", "organizations", type_="unique")
    op.drop_column("organizations", "name")
    # ### end Alembic commands ###
