"""add travel expense table

Revision ID: 010808b7d620
Revises: c45a1401ca21
Create Date: 2026-02-11 16:35:18.719052

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "010808b7d620"
down_revision: Union[str, Sequence[str], None] = "c45a1401ca21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic-please adjust! ###
    op.create_table(
        "travel_expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_location", sa.JSON(), nullable=False),
        sa.Column("to_location", sa.JSON(), nullable=False),
        sa.Column("from_date", sa.Date(), nullable=False),
        sa.Column("to_date", sa.Date(), nullable=False),
        sa.Column(
            "vehicle",
            sa.Enum("CAR", "BIKE", "BUS", "TRAIN", "FLIGHT", name="vehicles"),
            nullable=False,
        ),
        sa.Column(
            "vehicle_type",
            sa.Enum("PUBLIC", "PERSONAL", "COMPANY", name="vehicletypes"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFTED", "APPROVED", "REJECTED", "PENDING", name="travelexpensestatus"
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("distance", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column("customer_name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name="fk_travel_expenses_created_by_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_travel_expenses_project_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("travel_expenses")
    # ### Drop ENUM types ###
    op.execute("DROP TYPE IF EXISTS vehicles")
    op.execute("DROP TYPE IF EXISTS vehicletypes")
    op.execute("DROP TYPE IF EXISTS travelexpensestatus")
    # ### end Alembic commands ###
