"""update travel_expense distance column value

Revision ID: 1215fbe5cdec
Revises: 5eae83d084ea
Create Date: 2026-02-13 11:45:37.869502

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1215fbe5cdec"
down_revision: Union[str, Sequence[str], None] = "5eae83d084ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "travel_expenses",
        "distance",
        existing_type=sa.NUMERIC(precision=5, scale=1),
        type_=sa.Numeric(precision=8, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "travel_expenses",
        "distance",
        existing_type=sa.Numeric(precision=8, scale=2),
        type_=sa.NUMERIC(precision=5, scale=1),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
