"""change approval_level to int

Revision ID: 13f5fa6029d6
Revises: eefe5d0d308d
Create Date: 2026-01-09 10:14:21.084043

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13f5fa6029d6"
down_revision: Union[str, Sequence[str], None] = "eefe5d0d308d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_approval_matrix",
        "approval_level",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        postgresql_using="approval_level::integer",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_approval_matrix",
        "approval_level",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        postgresql_using="approval_level::varchar",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
