"""add trip table

Revision ID: 15eea074bda7
Revises: 4062759a6b3d
Create Date: 2026-03-04 14:54:59.758686

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "15eea074bda7"
down_revision: Union[str, Sequence[str], None] = "4062759a6b3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("destination", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("hotel_accommodation_needed", sa.Boolean(), nullable=False),
        sa.Column(
            "mode_of_travel",
            sa.Enum("FLIGHT", "TRAIN", "BUS", "OWN_VEHICLE", name="travelmode"),
            nullable=False,
        ),
        sa.Column("vehicle_needed", sa.Boolean(), nullable=False),
        sa.Column("advance_needed", sa.Boolean(), nullable=False),
        sa.Column("advance_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name="fk_trips_organization_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="fk_trips_project_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trips_id"), "trips", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trips_id"), table_name="trips")
    op.drop_table("trips")
    sa.Enum(name="travelmode").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
