"""add project_id in expenses

Revision ID: 15f184293f43
Revises: 7153c74f3e64
Create Date: 2025-12-16 16:55:14.262470

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "15f184293f43"
down_revision: Union[str, Sequence[str], None] = "7153c74f3e64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_expenses", sa.Column("project_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_user_expenses_project_id",
        "user_expenses",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_user_expenses_project_id", "user_expenses", type_="foreignkey"
    )
    op.drop_column("user_expenses", "project_id")
    # ### end Alembic commands ###
