"""add status to trip

Revision ID: 25796d907a0f
Revises: 15eea074bda7
Create Date: 2026-03-11 11:54:11.328256

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "25796d907a0f"
down_revision: Union[str, Sequence[str], None] = "15eea074bda7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    trip_status = sa.Enum(
        "SUBMITTED",
        "APPROVED",
        "REJECTED",
        name="tripstatus",
    )

    trip_status.create(op.get_bind())

    op.add_column(
        "trips",
        sa.Column(
            "status",
            trip_status,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trips", "status")
    sa.Enum(
        "SUBMITTED",
        "APPROVED",
        "REJECTED",
        name="tripstatus",
    ).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
