"""add more columns to grade

Revision ID: 2bdd6520000f
Revises: 13f5fa6029d6
Create Date: 2026-01-12 12:35:28.039507

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2bdd6520000f"
down_revision: Union[str, Sequence[str], None] = "13f5fa6029d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    train_class_enum = sa.Enum("TIER_3", "TIER_2", name="trainclassenum")
    train_class_enum.create(op.get_bind(), checkfirst=True)

    flight_class_enum = sa.Enum(
        "ECONOMY", "PREMIUM_ECONOMY", "BUSINESS", name="flightclassenum"
    )
    flight_class_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "grades",
        sa.Column(
            "train_class",
            train_class_enum,
            nullable=True,
        ),
    )
    op.add_column(
        "grades",
        sa.Column(
            "flight_class",
            flight_class_enum,
            nullable=True,
        ),
    )
    op.add_column(
        "grades",
        sa.Column(
            "domestic_accommodation_limit",
            sa.Numeric(precision=18, scale=2),
            nullable=True,
        ),
    )
    op.add_column(
        "grades",
        sa.Column(
            "international_accommodation_limit",
            sa.Numeric(precision=18, scale=2),
            nullable=True,
        ),
    )
    op.add_column(
        "grades",
        sa.Column(
            "food_daily_limit",
            sa.Numeric(precision=18, scale=2),
            nullable=True,
        ),
    )

    op.execute("UPDATE grades SET train_class = 'TIER_2' WHERE train_class IS NULL")
    op.alter_column(
        "grades",
        "train_class",
        nullable=False,
    )
    op.execute("UPDATE grades SET flight_class = 'ECONOMY' WHERE flight_class IS NULL")
    op.alter_column(
        "grades",
        "flight_class",
        nullable=False,
    )
    op.execute(
        "UPDATE grades SET domestic_accommodation_limit = 1000 WHERE domestic_accommodation_limit IS NULL"
    )
    op.alter_column(
        "grades",
        "domestic_accommodation_limit",
        nullable=False,
    )
    op.execute(
        "UPDATE grades SET international_accommodation_limit = 5000 WHERE international_accommodation_limit IS NULL"
    )
    op.alter_column(
        "grades",
        "international_accommodation_limit",
        nullable=False,
    )
    op.execute(
        "UPDATE grades SET food_daily_limit = 1000 WHERE food_daily_limit IS NULL"
    )
    op.alter_column(
        "grades",
        "food_daily_limit",
        nullable=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("grades", "food_daily_limit")
    op.drop_column("grades", "international_accommodation_limit")
    op.drop_column("grades", "domestic_accommodation_limit")
    op.drop_column("grades", "flight_class")
    op.drop_column("grades", "train_class")

    train_class_enum = sa.Enum("TIER_3", "TIER_2", name="trainclassenum")
    train_class_enum.drop(op.get_bind(), checkfirst=True)

    flight_class_enum = sa.Enum(
        "ECONOMY", "PREMIUM_ECONOMY", "BUSINESS", name="flightclassenum"
    )
    flight_class_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
