"""Add webhook provider and url to connections

Revision ID: 3149f9c24186
Revises: 40dc0a9a46a0
Create Date: 2026-01-06 11:35:32.186133

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3149f9c24186"
down_revision: Union[str, Sequence[str], None] = "40dc0a9a46a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("connections", sa.Column("url", sa.String(), nullable=True))
    op.execute("ALTER TYPE providertype ADD VALUE IF NOT EXISTS 'WEBHOOK'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("connections", "url")
    # ### end Alembic commands ###
