"""add assets table

Revision ID: 35da38f305c5
Revises: 6c0222f427cf
Create Date: 2025-12-24 11:52:24.111028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35da38f305c5"
down_revision: Union[str, Sequence[str], None] = "6c0222f427cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column(
            "category",
            sa.Enum("VEHICLE", "GENERATOR", name="assetcategory"),
            nullable=False,
        ),
        sa.Column(
            "vehicle_type",
            sa.Enum("SEDAN", "SUV", "VAN", "TRUCK", name="vehicletype"),
            nullable=True,
        ),
        sa.Column(
            "generator_type",
            sa.Enum("INDUSTRIAL_BACKUP_UNIT", name="generatortype"),
            nullable=True,
        ),
        sa.Column("asset_code", sa.String(), nullable=False),
        sa.Column("make_model", sa.String(), nullable=False),
        sa.Column(
            "fuel_type",
            sa.Enum(
                "PETROL",
                "DIESEL",
                "CNG",
                "LPG",
                "ELECTRIC",
                "HYBRID",
                "HYDROGEN",
                "NATURAL_GAS",
                "BIO_DIESEL",
                "DUAL_FUEL",
                name="fueltype",
            ),
            nullable=False,
        ),
        sa.Column("operator_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operator_user_id"],
            ["users.id"],
            name="fx_asset_operator_user_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name="fk_asset_organization_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assets_category"), "assets", ["category"], unique=False)
    op.create_index(op.f("ix_assets_id"), "assets", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assets_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_category"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
