"""migrate is_approver or is_manager to manager role

Revision ID: 3dd5b1822e08
Revises: 7337e13e1b49
Create Date: 2026-02-06 16:52:08.539745

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3dd5b1822e08"
down_revision: Union[str, Sequence[str], None] = "7337e13e1b49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    conn.execute(
        sa.text(
            """
            INSERT INTO roles (name, description)
            VALUES ('Manager', 'Can approve requests but can''t make changes.')
            ON CONFLICT (name) DO NOTHING
            """
        )
    )

    admin_role_id = conn.execute(
        sa.text(
            """
            SELECT id
            FROM roles
            WHERE name = 'Admin'
            """
        ),
    ).scalar()

    manager_role_id = conn.execute(
        sa.text(
            """
            SELECT id
            FROM roles
            WHERE name = 'Manager'
            """
        ),
    ).scalar()

    conn.execute(
        sa.text(
            """
            UPDATE users
            SET role_id = :manager_role_id
            WHERE role_id != :admin_role_id
                AND (
                    EXISTS (
                        SELECT 1
                        FROM projects
                        WHERE projects.manager_id = users.id
                    )
                    OR EXISTS (
                        SELECT 1
                        FROM project_approval_matrix
                        WHERE project_approval_matrix.approver_id = users.id
                    )
                )
            """
        ),
        {"manager_role_id": manager_role_id, "admin_role_id": admin_role_id},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    user_role_id = conn.execute(
        sa.text(
            """
            SELECT id
            FROM roles
            WHERE name = 'User'
            """
        ),
    ).scalar()

    manager_role_id = conn.execute(
        sa.text(
            """
            SELECT id
            FROM roles
            WHERE name = 'Manager'
            """
        ),
    ).scalar()

    conn.execute(
        sa.text(
            """
            UPDATE users
            SET role_id = :user_role_id
            WHERE role_id = :manager_role_id
            """
        ),
        {"user_role_id": user_role_id, "manager_role_id": manager_role_id},
    )
    # ### end Alembic commands ###
