"""user expense approval

Revision ID: 40dc0a9a46a0
Revises: ff5b52574d6e
Create Date: 2025-12-23 19:22:18.959851

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "40dc0a9a46a0"
down_revision: Union[str, Sequence[str], None] = "ff5b52574d6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_expense_approvals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_expense_id", sa.Integer(), nullable=False),
        sa.Column("approver_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "APPROVED", "REJECTED", "PENDING", "CANCELLED", name="approvalstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["users.id"],
            name="fk_user_expense_approvals_approver_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_expense_id"],
            ["user_expenses.id"],
            name="fk_user_expense_approvals_user_expense_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_expense_id", "approver_id", name="unique_user_expense_approver"
        ),
    )
    op.create_index(
        op.f("ix_user_expense_approvals_id"),
        "user_expense_approvals",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_expense_approvals_id"), table_name="user_expense_approvals"
    )
    op.drop_table("user_expense_approvals")
    # ### end Alembic commands ###
