"""add flight, train classes and accommodation type

Revision ID: 4a409176b440
Revises: 00e0188105f8
Create Date: 2026-01-14 16:35:37.050193

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a409176b440"
down_revision: Union[str, Sequence[str], None] = "00e0188105f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    train_class_enum = sa.Enum("TIER_3", "TIER_2", name="trainclassenum")
    train_class_enum.create(op.get_bind(), checkfirst=True)

    flight_class_enum = sa.Enum(
        "ECONOMY", "PREMIUM_ECONOMY", "BUSINESS", name="flightclassenum"
    )
    flight_class_enum.create(op.get_bind(), checkfirst=True)

    accommodation_type = sa.Enum("DOMESTIC", "INTERNATIONAL", name="accommodationtype")
    accommodation_type.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "expenses",
        sa.Column(
            "train_class",
            train_class_enum,
            nullable=True,
        ),
    )
    op.add_column(
        "expenses",
        sa.Column(
            "flight_class",
            flight_class_enum,
            nullable=True,
        ),
    )
    op.add_column(
        "expenses",
        sa.Column(
            "accommodation_type",
            accommodation_type,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expenses", "accommodation_type")
    op.drop_column("expenses", "flight_class")
    op.drop_column("expenses", "train_class")

    train_class_enum = sa.Enum("TIER_3", "TIER_2", name="trainclassenum")
    train_class_enum.drop(op.get_bind(), checkfirst=True)

    flight_class_enum = sa.Enum(
        "ECONOMY", "PREMIUM_ECONOMY", "BUSINESS", name="flightclassenum"
    )
    flight_class_enum.drop(op.get_bind(), checkfirst=True)

    accommodation_type = sa.Enum("DOMESTIC", "INTERNATIONAL", name="accommodationtype")
    accommodation_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
