"""add travel expense notes and update travel expense column

Revision ID: 55c11dcebc9e
Revises: d70c7f3b1496
Create Date: 2026-02-20 17:32:21.177456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55c11dcebc9e"
down_revision: Union[str, Sequence[str], None] = "d70c7f3b1496"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "travel_expense_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("file_name", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expense_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name="fk_travel_expense_notes_created_by_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["travel_expenses.id"],
            name="fk_travel_expense_notes_expense_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "travel_expenses",
        sa.Column("duration_seconds", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("travel_expenses", "duration_seconds")
    op.drop_table("travel_expense_notes")
    # ### end Alembic commands ###
