"""remove ll1 and llm2 processed data

Revision ID: 5bf450eebdcd
Revises: 040b3440cf96
Create Date: 2025-12-03 13:05:44.440031

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5bf450eebdcd"
down_revision: Union[str, Sequence[str], None] = "040b3440cf96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("extracted_expenses", "processed_data_llm2")
    op.drop_column("extracted_expenses", "processed_data_llm1")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "extracted_expenses",
        sa.Column(
            "processed_data_llm1",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "extracted_expenses",
        sa.Column(
            "processed_data_llm2",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
