"""add carbon emission column in travel expenses

Revision ID: 5e38507e86f1
Revises: f2461ed2b5e9
Create Date: 2026-02-25 12:31:01.874379

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e38507e86f1"
down_revision: Union[str, Sequence[str], None] = "f2461ed2b5e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "travel_expenses",
        sa.Column("carbon_emission", sa.Numeric(precision=10, scale=3), nullable=True),
    )
    op.alter_column(
        "travel_expenses",
        "duration_seconds",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    op.execute(
        """
    UPDATE travel_expenses
    SET carbon_emission =
    CASE
        WHEN Vehicle = 'CAR' THEN 0.171
        WHEN Vehicle = 'BIKE' THEN 0.101
        ELSE 0.0
    END
    WHERE carbon_emission IS NULL
    """
    )
    op.alter_column("travel_expenses", "carbon_emission", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "travel_expenses",
        "duration_seconds",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    op.drop_column("travel_expenses", "carbon_emission")
    # ### end Alembic commands ###
