"""add new fields in user table

Revision ID: 5e70788586f6
Revises: 8eedd72a74f4
Create Date: 2025-12-09 16:11:30.066458

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e70788586f6"
down_revision: Union[str, Sequence[str], None] = "8eedd72a74f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add as nullable
    op.add_column("users", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("last_name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("mobile_number", sa.String(), nullable=True))

    # Step 2: Populate existing rows
    conn = op.get_bind()
    conn.execute(
        sa.text("""
        UPDATE users
        SET first_name = 'Unknown',
            last_name = 'User'
        WHERE first_name IS NULL OR last_name IS NULL;
    """)
    )

    # Step 3: Make non-nullable
    op.alter_column("users", "first_name", nullable=False)
    op.alter_column("users", "last_name", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "mobile_number")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
