"""add car_mileage_rate and bike_mileage_rate in grade

Revision ID: 5eae83d084ea
Revises: 010808b7d620
Create Date: 2026-02-12 11:28:38.327473

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5eae83d084ea"
down_revision: Union[str, Sequence[str], None] = "010808b7d620"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "grades",
        sa.Column(
            "car_mileage_rate",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "grades",
        sa.Column(
            "bike_mileage_rate",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
            server_default="0",
        ),
    )

    op.alter_column("grades", "car_mileage_rate", server_default=None)
    op.alter_column("grades", "bike_mileage_rate", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("grades", "bike_mileage_rate")
    op.drop_column("grades", "car_mileage_rate")
    # ### end Alembic commands ###
