"""add submitted_at to user expense

Revision ID: 629befb87921
Revises: 63f09a19f380
Create Date: 2026-02-02 16:51:39.217501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "629befb87921"
down_revision: Union[str, Sequence[str], None] = "63f09a19f380"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_expenses",
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_expenses", "submitted_at")
    # ### end Alembic commands ###
