"""add TIER_1 to Trainclass enum

Revision ID: 63f09a19f380
Revises: 76ced91326fd
Create Date: 2026-02-02 17:49:26.754171

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63f09a19f380"
down_revision: Union[str, Sequence[str], None] = "76ced91326fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE trainclassenum ADD VALUE IF NOT EXISTS 'TIER_1'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
