"""Added a connection and whatsapp tables

Revision ID: 6c0222f427cf
Revises: e6ddb802cb7a
Create Date: 2025-12-23 10:16:56.238700

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6c0222f427cf"
down_revision: Union[str, Sequence[str], None] = "e6ddb802cb7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column(
            "provider_type", sa.Enum("WHATSAPP", name="providertype"), nullable=False
        ),
        sa.Column(
            "source_type", sa.Enum("INPUT", "OUTPUT", name="sourcetype"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("CONNECTED", "DISCONNECTED", name="connectionstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_connections_id"), "connections", ["id"], unique=False)
    op.create_table(
        "whatsapp_configurations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "phone_number_id",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column(
            "access_token", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column(
            "verification_token",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=False,
        ),
        sa.Column("connection_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"], ["connections.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_whatsapp_configurations_id"),
        "whatsapp_configurations",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_whatsapp_configurations_id"), table_name="whatsapp_configurations"
    )
    op.drop_table("whatsapp_configurations")
    op.drop_index(op.f("ix_connections_id"), table_name="connections")
    op.drop_table("connections")
    # ### end Alembic commands ###
