"""add connection_id column in expenses

Revision ID: 7337e13e1b49
Revises: c3cff725996e
Create Date: 2026-02-10 12:06:54.520316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7337e13e1b49"
down_revision: Union[str, Sequence[str], None] = "c3cff725996e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expenses", sa.Column("connection_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_expenses_connection_id",
        "expenses",
        "connections",
        ["connection_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_expenses_connection_id", "expenses", type_="foreignkey")
    op.drop_column("expenses", "connection_id")
    # ### end Alembic commands ###
