"""add document_no to expenses

Revision ID: 76ced91326fd
Revises: 7f61861c506b
Create Date: 2026-02-02 11:36:28.687365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76ced91326fd"
down_revision: Union[str, Sequence[str], None] = "7f61861c506b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expenses", sa.Column("document_no", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expenses", "document_no")
    # ### end Alembic commands ###
