"""add grade_id fk in users table

Revision ID: 78fbebd59c82
Revises: 9c6b520bde2a
Create Date: 2025-11-07 14:38:51.771474

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import Integer, column, exists, select, table


# revision identifiers, used by Alembic.
revision: str = "78fbebd59c82"
down_revision: Union[str, Sequence[str], None] = "9c6b520bde2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("grade_id", sa.Integer(), nullable=True))

    grades = table(
        "grades",
        column("id", Integer),
        column("organization_id", Integer),
        column("expense_limit", Integer),
    )

    users = table(
        "users",
        column("id", Integer),
        column("organization_id", Integer),
        column("grade_id", Integer),
    )

    organizations = table("organizations", column("id", Integer))

    conn = op.get_bind()
    org_ids = conn.execute(select(organizations.c.id)).fetchall()

    for (org_id,) in org_ids:
        grade_exists = conn.scalar(
            select(exists().where(grades.c.organization_id == org_id))
        )
        if not grade_exists:
            conn.execute(
                grades.insert().values(
                    organization_id=org_id,
                    expense_limit=1000,
                )
            )
    conn.execute(
        users.update().values(
            grade_id=select(grades.c.id)
            .where(grades.c.organization_id == users.c.organization_id)
            .scalar_subquery()
        )
    )

    op.alter_column("users", "grade_id", nullable=False)

    op.create_foreign_key(
        "fk_users_grade_id",
        "users",
        "grades",
        ["grade_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_grade_id", "users", type_="foreignkey")
    op.drop_column("users", "grade_id")
    # ### end Alembic commands ###
