"""add bill date to expense table

Revision ID: 7a3b3d016c6f
Revises: 5bf450eebdcd
Create Date: 2025-12-04 13:22:52.894897

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7a3b3d016c6f"
down_revision: Union[str, Sequence[str], None] = "5bf450eebdcd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expenses",
        sa.Column("bill_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expenses", "bill_date")
    # ### end Alembic commands ###
