"""add created_by and remove organization_id from trips

Revision ID: 81c1e485c3c3
Revises: 25796d907a0f
Create Date: 2026-03-11 12:47:16.525864

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81c1e485c3c3"
down_revision: Union[str, Sequence[str], None] = "25796d907a0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trips", sa.Column("created_by", sa.Integer(), nullable=False))
    op.drop_constraint(op.f("fk_trips_organization_id"), "trips", type_="foreignkey")
    op.create_foreign_key(
        "fk_trips_created_by",
        "trips",
        "users",
        ["created_by"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("trips", "organization_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trips",
        sa.Column("organization_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("fk_trips_created_by", "trips", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_trips_organization_id"),
        "trips",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("trips", "created_by")
    # ### end Alembic commands ###
