"""add role_id and employee_id to user

Revision ID: 8320eeea0efc
Revises: 35da38f305c5
Create Date: 2025-12-26 10:30:10.544247

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8320eeea0efc"
down_revision: Union[str, Sequence[str], None] = "35da38f305c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'roles_name_key'
            ) THEN
                ALTER TABLE roles DROP CONSTRAINT roles_name_key;
            END IF;
        END
        $$;
        """)

    op.add_column("users", sa.Column("code", sa.String(), nullable=True))
    op.add_column("users", sa.Column("role_id", sa.Integer(), nullable=True))

    op.execute("""
        UPDATE users
        SET code = 'Default_' || id
        WHERE code IS NULL
    """)

    op.execute("""
        INSERT INTO roles (name, description, organization_id, created_at, updated_at)
        SELECT
            'Admin',
            'Can manage all settings, users, and data.',
            o.id,
            NOW(),
            NOW()
        FROM organizations o
        WHERE NOT EXISTS (
            SELECT 1
            FROM roles r
            WHERE r.name = 'Admin'
              AND r.organization_id = o.id
        )
    """)

    op.execute("""
        UPDATE users
        SET role_id = r.id
        FROM roles r
        WHERE r.name = 'Admin'
          AND r.organization_id = users.organization_id
          AND users.role_id IS NULL
    """)

    op.alter_column("users", "code", nullable=False)
    op.alter_column("users", "role_id", nullable=False)

    op.drop_constraint(op.f("users_mobile_number_key"), "users", type_="unique")
    op.create_unique_constraint(
        "uq_users_code_organization_id", "users", ["code", "organization_id"]
    )
    op.create_unique_constraint(
        "uq_users_mobile_number_organization_id",
        "users",
        ["mobile_number", "organization_id"],
    )
    op.create_foreign_key(
        "fk_users_role_id", "users", "roles", ["role_id"], ["id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_role_id", "users", type_="foreignkey")
    op.drop_constraint(
        "uq_users_mobile_number_organization_id", "users", type_="unique"
    )
    op.drop_constraint("uq_users_code_organization_id", "users", type_="unique")
    op.create_unique_constraint(
        op.f("users_mobile_number_key"),
        "users",
        ["mobile_number"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("users", "role_id")
    op.drop_column("users", "code")
    # ### end Alembic commands ###
