"""expense daily and monthly tables

Revision ID: 8eedd72a74f4
Revises: 31fa2d6e92d8
Create Date: 2025-12-08 18:33:30.564424

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8eedd72a74f4"
down_revision: Union[str, Sequence[str], None] = "31fa2d6e92d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_daily_expenses",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("daily_spent", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.PrimaryKeyConstraint("user_id", "day"),
    )
    op.create_table(
        "user_monthly_expenses",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("monthly_spent", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.PrimaryKeyConstraint("user_id", "month"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_monthly_expenses")
    op.drop_table("user_daily_expenses")
    # ### end Alembic commands ###
