"""update travel expense duration hours to not null

Revision ID: 938b9e82cec7
Revises: 55c11dcebc9e
Create Date: 2026-02-20 18:16:29.454582

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "938b9e82cec7"
down_revision: Union[str, Sequence[str], None] = "55c11dcebc9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE travel_expenses
        SET duration_seconds = 1.00
        WHERE duration_seconds IS NULL
        """
    )

    op.alter_column("travel_expenses", "duration_seconds", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("travel_expenses", "duration_seconds", nullable=True)

    # ### end Alembic commands ###
