"""remove currency from grades

Revision ID: 951a896035bd
Revises: 2bdd6520000f
Create Date: 2026-01-13 15:46:01.186776

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "951a896035bd"
down_revision: Union[str, Sequence[str], None] = "2bdd6520000f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("grades", "currency")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "grades",
        sa.Column("currency", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
