"""restrict user delete on user_expense_approvals presence

Revision ID: 96f36f5eb5da
Revises: 5e38507e86f1
Create Date: 2026-02-25 15:59:48.953821

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96f36f5eb5da"
down_revision: Union[str, Sequence[str], None] = "5e38507e86f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_expense_approvals_approver_id"),
        "user_expense_approvals",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_user_expense_approvals_approver_id",
        "user_expense_approvals",
        "users",
        ["approver_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_user_expense_approvals_approver_id",
        "user_expense_approvals",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_user_expense_approvals_approver_id"),
        "user_expense_approvals",
        "users",
        ["approver_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
