"""add user expenses."""

"""add user_expenses

Revision ID: 9c6b520bde2a
Revises: 0426369d3961
Create Date: 2025-11-07 12:39:05.928012

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c6b520bde2a"
down_revision: Union[str, Sequence[str], None] = "0426369d3961"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expense_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "EXTRACTING",
                "EXTRACTED",
                "SPLITTING",
                "PENDING",
                "APPROVED",
                "REJECTED",
                name="expensestatus",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses.id"],
            name="fk_user_expenses_expense_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_user_expenses_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_expenses_id"), "user_expenses", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_expenses_status"), "user_expenses", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_expenses_status"), table_name="user_expenses")
    op.drop_index(op.f("ix_user_expenses_id"), table_name="user_expenses")
    op.drop_table("user_expenses")
    op.execute("DROP TYPE IF EXISTS expensestatus CASCADE")
    # ### end Alembic commands ###
