"""add trip id to user expense

Revision ID: 9fa563d13e83
Revises: 81c1e485c3c3
Create Date: 2026-03-06 16:36:30.249621

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9fa563d13e83"
down_revision: Union[str, Sequence[str], None] = "81c1e485c3c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_expenses", sa.Column("trip_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_user_expenses_trip_id",
        "user_expenses",
        "trips",
        ["trip_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_expenses_trip_id", "user_expenses", type_="foreignkey")
    op.drop_column("user_expenses", "trip_id")
    # ### end Alembic commands ###
