"""add vendor_name to expense

Revision ID: a7131013d8d3
Revises: 26543cf589b6
Create Date: 2026-01-22 10:04:57.433406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a7131013d8d3"
down_revision: Union[str, Sequence[str], None] = "26543cf589b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expenses",
        sa.Column("vendor_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expenses", "vendor_name")
    # ### end Alembic commands ###
