"""add created_by to expense

Revision ID: bd1f364f1a00
Revises: 951a896035bd
Create Date: 2026-01-13 18:59:04.746138

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd1f364f1a00"
down_revision: Union[str, Sequence[str], None] = "951a896035bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expenses", sa.Column("created_by", sa.Integer(), nullable=True))

    op.execute(
        """
        UPDATE expenses e
        SET created_by = ue.user_id
        FROM user_expenses ue
        WHERE ue.expense_id = e.id;
    """
    )

    op.execute(
        """
        DELETE FROM expenses
        WHERE created_by IS NULL;
    """
    )

    op.alter_column("expenses", "created_by", nullable=False)

    op.create_foreign_key(
        "fk_expenses_created_by",
        "expenses",
        "users",
        ["created_by"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_expenses_created_by", "expenses", type_="foreignkey")
    op.drop_column("expenses", "created_by")
    # ### end Alembic commands ###
