"""add monthly and total budget, remove budget and budget type

Revision ID: c3cff725996e
Revises: e81d43ce8096
Create Date: 2026-02-03 12:20:52.801690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c3cff725996e"
down_revision: Union[str, Sequence[str], None] = "e81d43ce8096"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("monthly_budget", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "projects",
        sa.Column("total_budget", sa.Numeric(precision=12, scale=2), nullable=True),
    )

    op.execute(
        """
        UPDATE projects
        SET monthly_budget = 0,
            total_budget = budget
        WHERE monthly_budget IS NULL
           OR total_budget IS NULL
        """
    )

    op.alter_column("projects", "monthly_budget", nullable=False)
    op.alter_column("projects", "total_budget", nullable=False)

    op.drop_column("projects", "budget")
    op.drop_column("projects", "budget_type")

    op.execute("DROP TYPE IF EXISTS budgettype")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE TYPE budgettype AS ENUM ('MONTHLY', 'YEARLY')")

    op.add_column(
        "projects",
        sa.Column(
            "budget_type",
            postgresql.ENUM("MONTHLY", "YEARLY", name="budgettype"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "budget",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE projects
        SET
            budget = monthly_budget,
            budget_type = 'MONTHLY'
        WHERE budget IS NULL
           OR budget_type IS NULL
        """
    )

    op.alter_column("projects", "budget", nullable=False)
    op.alter_column("projects", "budget_type", nullable=False)

    op.drop_column("projects", "total_budget")
    op.drop_column("projects", "monthly_budget")
    # ### end Alembic commands ###
