"""make user_id as fk in expense tracking

Revision ID: c5e238d34346
Revises: d1f22af41a6a
Create Date: 2026-03-20 12:23:52.137568

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5e238d34346"
down_revision: Union[str, Sequence[str], None] = "d1f22af41a6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_user_daily_expenses_user_id",
        "user_daily_expenses",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_user_monthly_expenses_user_id",
        "user_monthly_expenses",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_user_monthly_expenses_user_id", "user_monthly_expenses", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_user_daily_expenses_user_id", "user_daily_expenses", type_="foreignkey"
    )
    # ### end Alembic commands ###
