"""change unique constraints in project approval matrix

Revision ID: d503a84b8bec
Revises: 6aa0ae7ab037
Create Date: 2026-02-06 15:38:51.911711

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d503a84b8bec"
down_revision: Union[str, Sequence[str], None] = "6aa0ae7ab037"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DELETE FROM project_approval_matrix a
        USING project_approval_matrix b
        WHERE a.project_id = b.project_id
          AND a.approver_id = b.approver_id
          AND a.approval_level > b.approval_level
    """)

    op.execute("""
        DELETE FROM project_approval_matrix a
        USING project_approval_matrix b
        WHERE a.project_id = b.project_id
          AND a.approval_level = b.approval_level
          AND a.approver_id > b.approver_id
    """)

    op.drop_constraint(
        op.f("uq_project_id_approver_id_approval_level"),
        "project_approval_matrix",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_project_approval_project_approval_level",
        "project_approval_matrix",
        ["project_id", "approval_level"],
    )
    op.create_unique_constraint(
        "uq_project_approval_project_approver",
        "project_approval_matrix",
        ["project_id", "approver_id"],
    )

    op.add_column(
        "user_expenses",
        sa.Column("highest_approved_level", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_expenses", "highest_approved_level")
    op.drop_constraint(
        "uq_project_approval_project_approver",
        "project_approval_matrix",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_project_id_approver_id_approval_level"),
        "project_approval_matrix",
        ["project_id", "approver_id", "approval_level"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(
        "uq_project_approval_project_approval_level",
        "project_approval_matrix",
        type_="unique",
    )
    # ### end Alembic commands ###
