"""add approver level and update unique constraint

Revision ID: d70c7f3b1496
Revises: d503a84b8bec
Create Date: 2026-02-16 15:24:53.852756

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d70c7f3b1496"
down_revision: Union[str, Sequence[str], None] = "d503a84b8bec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "user_expense_approvals",
        sa.Column("approval_level", sa.Integer(), nullable=True),
    )

    op.execute("""
        DELETE FROM user_expense_approvals a
        USING user_expense_approvals b
        WHERE a.user_expense_id = b.user_expense_id
          AND a.status = 'PENDING'
          AND b.status = 'PENDING'
          AND a.id > b.id
    """)

    op.execute("""
        DELETE FROM user_expense_approvals p
        USING user_expense_approvals r
        WHERE p.user_expense_id = r.user_expense_id
          AND r.status = 'REJECTED'
          AND p.status = 'PENDING'
    """)

    op.execute("""
        DELETE FROM user_expense_approvals a
        USING user_expense_approvals b
        WHERE a.user_expense_id = b.user_expense_id
          AND a.status = 'REJECTED'
          AND b.status = 'REJECTED'
          AND a.id > b.id
    """)

    op.execute("""
        WITH ranked AS (
            SELECT
                id,
                ROW_NUMBER() OVER (
                    PARTITION BY user_expense_id
                    ORDER BY id
                ) AS lvl
            FROM user_expense_approvals
            WHERE status = 'APPROVED'
        )
        UPDATE user_expense_approvals u
        SET approval_level = ranked.lvl
        FROM ranked
        WHERE u.id = ranked.id
    """)

    op.execute("""
        UPDATE user_expenses ue
        SET highest_approved_level = a.max_lvl
        FROM (
            SELECT
                user_expense_id,
                MAX(approval_level) AS max_lvl
            FROM user_expense_approvals
            WHERE status = 'APPROVED'
            GROUP BY user_expense_id
        ) a
        WHERE ue.id = a.user_expense_id
    """)

    op.execute("""
        UPDATE user_expense_approvals r
        SET approval_level = a.max_lvl + 1
        FROM (
            SELECT user_expense_id, COALESCE(MAX(approval_level), 0) AS max_lvl
            FROM user_expense_approvals
            GROUP BY user_expense_id
        ) a
        WHERE r.user_expense_id = a.user_expense_id
          AND r.status = 'REJECTED'
    """)

    op.execute("""
        UPDATE user_expense_approvals p
        SET approval_level = a.max_lvl + 1
        FROM (
            SELECT user_expense_id, COALESCE(MAX(approval_level), 0) AS max_lvl
            FROM user_expense_approvals
            GROUP BY user_expense_id
        ) a
        WHERE p.user_expense_id = a.user_expense_id
          AND p.status = 'PENDING'
    """)

    op.alter_column(
        "user_expense_approvals",
        "approval_level",
        nullable=False,
    )

    op.drop_constraint(
        op.f("unique_user_expense_approver"),
        "user_expense_approvals",
        type_="unique",
    )
    op.create_unique_constraint(
        "unique_user_expense_approver_level",
        "user_expense_approvals",
        ["user_expense_id", "approver_id", "approval_level"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "unique_user_expense_approver_level",
        "user_expense_approvals",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("unique_user_expense_approver"),
        "user_expense_approvals",
        ["user_expense_id", "approver_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("user_expense_approvals", "approval_level")
    # ### end Alembic commands ###
