"""add categorytype subcategorytype enum

Revision ID: e81d43ce8096
Revises: 629befb87921
Create Date: 2026-02-05 17:52:58.711271

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e81d43ce8096"
down_revision: Union[str, Sequence[str], None] = "629befb87921"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    category_enum = sa.Enum(
        "TRAVEL",
        "HOTEL_ACCOMMODATION",
        "MEALS_FOOD",
        "STATIONERY",
        "FUEL_GAS",
        "OTHERS",
        name="categorytype",
    )
    category_enum.create(op.get_bind(), checkfirst=True)

    subcategory_enum = sa.Enum(
        "GENERAL",
        "AUTO_BIKE_TAXI",
        "BUS",
        "TRAIN",
        "FLIGHT_INVOICE",
        "FLIGHT_RECEIPT",
        "INVOICE",
        "RECEIPT",
        name="subcategorytype",
    )
    subcategory_enum.create(op.get_bind(), checkfirst=True)

    # Normalize categories to uppercase and map invalid values to OTHERS
    op.execute(
        """
        UPDATE expenses
        SET category = CASE
            WHEN UPPER(category) IN ('TRAVEL', 'HOTEL_ACCOMMODATION', 'MEALS_FOOD', 'STATIONERY', 'FUEL_GAS', 'OTHERS')
                THEN UPPER(category)
            ELSE 'OTHERS'
        END
        WHERE category IS NOT NULL;
    """
    )

    # Normalize subcategories to uppercase and map invalid values to GENERAL
    op.execute(
        """
        UPDATE expenses
        SET sub_category = CASE
            WHEN UPPER(sub_category) IN ('GENERAL', 'AUTO_BIKE_TAXI', 'BUS', 'TRAIN', 'FLIGHT_INVOICE', 'FLIGHT_RECEIPT', 'INVOICE', 'RECEIPT')
                THEN UPPER(sub_category)
            ELSE 'GENERAL'
        END
        WHERE sub_category IS NOT NULL;
    """
    )

    op.alter_column(
        "expenses",
        "category",
        existing_type=sa.VARCHAR(),
        type_=category_enum,
        postgresql_using="category::categorytype",
        existing_nullable=True,
    )
    op.alter_column(
        "expenses",
        "sub_category",
        existing_type=sa.VARCHAR(),
        type_=subcategory_enum,
        postgresql_using="sub_category::subcategorytype",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expenses",
        "sub_category",
        existing_type=sa.Enum(
            "GENERAL",
            "AUTO_BIKE_TAXI",
            "BUS",
            "TRAIN",
            "FLIGHT_INVOICE",
            "FLIGHT_RECEIPT",
            "INVOICE",
            "RECEIPT",
            name="subcategorytype",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "expenses",
        "category",
        existing_type=sa.Enum(
            "TRAVEL",
            "HOTEL_ACCOMMODATION",
            "MEALS_FOOD",
            "STATIONERY",
            "FUEL_GAS",
            "OTHERS",
            name="categorytype",
        ),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )

    op.execute(
        """
        UPDATE expenses
        SET category = LOWER(category)
        WHERE category IS NOT NULL;
    """
    )

    op.execute(
        """
        UPDATE expenses
        SET sub_category = LOWER(sub_category)
        WHERE sub_category IS NOT NULL;
    """
    )

    op.execute("DROP TYPE IF EXISTS subcategorytype;")
    op.execute("DROP TYPE IF EXISTS categorytype;")
    # ### end Alembic commands ###
