"""add reject reson column in travel expenses table

Revision ID: f2461ed2b5e9
Revises: 938b9e82cec7
Create Date: 2026-02-24 10:57:53.835106

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f2461ed2b5e9"
down_revision: Union[str, Sequence[str], None] = "938b9e82cec7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "travel_expenses", sa.Column("reject_reason", sa.String(), nullable=True)
    )
    op.alter_column(
        "travel_expenses",
        "duration_seconds",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "travel_expenses",
        "duration_seconds",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
    )
    op.drop_column("travel_expenses", "reject_reason")
    # ### end Alembic commands ###
