"""add unique constraint to asset table

Revision ID: ff5b52574d6e
Revises: 8320eeea0efc
Create Date: 2025-12-24 18:29:00.684295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff5b52574d6e"
down_revision: Union[str, Sequence[str], None] = "8320eeea0efc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_assets_org_asset_code", "assets", ["organization_id", "asset_code"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_assets_org_asset_code", "assets", type_="unique")
    # ### end Alembic commands ###
